entity_config:
    ownership:
        entity:
            items:
                inventory_units:
                    options:
                        create_only:        true
                        priority:           100
                        indexed:            true
                    grid:
                        type:               select
                        label:              'Inventory Unit'
                        filter_type:        choice
                        required:           true
                        sortable:           true
                        filterable:         true
                        show_filter:        true
#                        choices:            "@kiboko_pms.pricing.form.type.inventory_units->getOwnershipsArray"
                    form:
                        type:               oro_type_choice_inventory_units
                        options:
                            block:          other
                            required:       true
                            label:          'Inventory Unit'

