navigation:
  menu_config:
    items:
      kiboko_pricing_tab:
        label: Pricing
        uri:   '#'
        extras:
          position: 5
      kiboko_products:
        label: Products
        route: kiboko_pms_pricing_product
    tree:
      application_menu:
        children:
          kiboko_pricing_tab:
            children:
              kiboko_products: ~

#  titles:
#    kiboko_price_list: Price List
