navigation:
  menu_config:
    items:
      kiboko_catalog_tab:
        label: Catalog
        uri:   '#'
        extras:
          position: 5
      kiboko_catalog_products:
        label: Products
        route: kiboko_mms_catalog_product_index
    tree:
      application_menu:
        children:
          kiboko_catalog_tab:
            children:
              kiboko_catalog_products: ~

#  titles:
#    kiboko_price_list: Price List
