services:
    kiboko_pms.importexport.data_converter:
        parent: oro_importexport.data_converter.configurable

    kiboko_pms.importexport.processor.export:
        parent: oro_importexport.processor.export_abstract
        calls:
            - [setDataConverter, ['@kiboko_pms.importexport.data_converter']]
        tags:
            - name: oro_importexport.processor
              type: export
              entity: AppBundle\Entity\Task
              alias: kiboko_pms_task
    kiboko_pms.importexport.processor.import:
        parent: oro_importexport.processor.import_abstract
        calls:
            - [setDataConverter, ['@kiboko_pms.importexport.data_converter']]
        tags:
            - name: oro_importexport.processor
              type: import
              entity: AppBundle\Entity\Task
              alias: kiboko_pms_task
