datagrids:
  kiboko-pms-products-datagrid:
    source:
      type: orm
      query:
        select:
          - p
          - COUNT(priceLists.id) as priceListsCount
        from:
          - { table: KibokoPricingBundle:Product, alias: p }
        join:
          left:
            - { join: p.priceLists, alias: priceLists }
    columns:
      name:
        label: kiboko_pms.pricing.price_list.grid.columns.name
      sku:
        label: kiboko_pms.pricing.price_list.grid.columns.sku
      priceListsCount:
        label: kiboko_pms.pricing.price_list.grid.columns.priceListsCount
    filters:
      columns:
        name:
          type: string
          data_name: p.name
        sku:
          type: string
          data_name: p.sku
    sorters:
      columns:
        name:
          data_name: p.name
        sku:
          data_name: p.sku
      default:
        sku: DESC

    properties:
      id: ~
      view_link:
        type:   url
        route:  kiboko_pms_pricing_price_list
        params:
          id: id
    actions:
      view:
        type: navigate
        label: oro.grid.action.view
        link: view_link
        icon: eye
        rowAction: true

  kiboko-pms-price-list-datagrid:
    source:
      type: orm
      query:
        select:
          - pl
          - COUNT(prices.id) as pricesCount
          - product.name
        from:
          - { table: KibokoPricingBundle:PriceList, alias: pl }
        join:
          left:
            - { join: pl.prices, alias: prices }
            - { join: pl.product, alias: product }
        where:
          and:
            - product.id = :productId
      bind_parameters:
        productId: productId
    columns:
      name:
        label: kiboko_pms.pricing.price_list.grid.columns.name
      active:
        label: kiboko_pms.pricing.price_list.grid.columns.active
        frontend_type: boolean
      start:
        label: kiboko_pms.pricing.price_list.grid.columns.start
        frontend_type: datetime
      end:
        label: kiboko_pms.pricing.price_list.grid.columns.end
        frontend_type: datetime
      pricesCount:
        label: kiboko_pms.pricing.price_list.grid.columns.pricesCount
