datagrids:
  kiboko-mms-price-list-datagrid:
    source:
      type: orm
      query:
        select:
          - pl
          - COUNT(prices.id) as pricesCount
          - product.name as productName
          - product.sku as productSku
          - customerSegment.name as segmentName
        from:
          - { table: KibokoPricingBundle:PriceList, alias: pl }
        join:
          left:
            - { join: pl.prices, alias: prices }
            - { join: pl.product, alias: product }
            - { join: pl.customerSegment, alias: customerSegment }
        where:
          and:
            - product.id = :productId
      bind_parameters:
        productId: productId
    columns:
      productName:
        label: kiboko_mms.pricing.price_list.grid.columns.productName
      productSku:
        label: kiboko_mms.pricing.price_list.grid.columns.productSku
      segmentName:
        label: kiboko_mms.pricing.price_list.grid.columns.segmentName
      active:
        label: kiboko_mms.pricing.price_list.grid.columns.active
        frontend_type: boolean
      start:
        label: kiboko_mms.pricing.price_list.grid.columns.start
        frontend_type: datetime
      end:
        label: kiboko_mms.pricing.price_list.grid.columns.end
        frontend_type: datetime
      pricesCount:
        label: kiboko_mms.pricing.price_list.grid.columns.pricesCount

    properties:
      id: ~
      price_history_link:
        type:   url
        route:  kiboko_mms_pricing_customer_segment_price_history
        params:
          productId: product.id
          customerSegmentId: customerSegment.id
    actions:
      price_history_view:
        type: navigate
        label: oro.grid.action.view
        link: price_history_link
        icon: time
        rowAction: true

  kiboko-mms-price-history-datagrid:
    source:
      type: orm
      query:
        select:
          - ph
          - ph.amount as priceAmount
          - ph.currencyCode as priceCurrency
          - customerSegment.name as customerSegmentName
        from:
          - { table: KibokoPricingBundle:PriceHistory, alias: ph }
        join:
          left:
            - { join: ph.price, alias: price }
            - { join: price.priceList, alias: priceList }
            - { join: priceList.product, alias: product }
            - { join: priceList.customerSegment, alias: customerSegment }
        where:
          and:
            - product.id = :productId
      bind_parameters:
        productId: productId
    columns:
      date:
        label: kiboko_mms.pricing.price_history.grid.columns.date
        frontend_type: datetime
      priceAmount:
        label: kiboko_mms.pricing.price_history.grid.columns.priceAmount
      priceCurrency:
        label: kiboko_mms.pricing.price_history.grid.columns.priceCurrency
      customerSegmentName:
        label: kiboko_mms.pricing.price_history.grid.columns.customerSegmentName
    filters:
      columns:
        date:
          type: datetime
          data_name: ph.date
        amount:
          type: number-range
          data_name: ph.amount
        amount:
          type: choice
          data_name: ph.currencyCode
        customerSegment:
          type: choice
          data_name: customerSegment.name
    sorters:
      columns:
        date:
          data_name: ph.date
        priceAmount:
          data_name: ph.amount
        priceCurrency:
          data_name: ph.currencyCode
        customerSegmentName:
          data_name: customerSegment.name
      default:
        date: DESC

  kiboko-mms-customer-segment-price-history-datagrid:
    source:
      type: orm
      query:
        select:
          - ph
          - ph.amount as priceAmount
          - ph.currencyCode as priceCurrency
        from:
          - { table: KibokoPricingBundle:PriceHistory, alias: ph }
        join:
          left:
            - { join: ph.price, alias: price }
            - { join: price.priceList, alias: priceList }
            - { join: priceList.product, alias: product }
            - { join: priceList.customerSegment, alias: customerSegment }
        where:
          and:
            - product.id = :productId
            - customerSegment.id = :customerSegmentId
      bind_parameters:
        productId: productId
        customerSegmentId: customerSegmentId
    columns:
      date:
        label: kiboko_mms.pricing.price_list.grid.columns.date
        frontend_type: datetime
      priceAmount:
        label: kiboko_mms.pricing.price_list.grid.columns.priceAmount
      priceCurrency:
        label: kiboko_mms.pricing.price_list.grid.columns.priceCurrency
      customerSegmentName:
        label: kiboko_mms.pricing.price_list.grid.columns.customerSegmentName
