navigation:
  menu_config:
    items:
      kiboko_pricing_tab:
        label: Pricing
        uri:   '#'
        extras:
          position: 5
      kiboko_pricing_history:
        label: Catalog
        route: kiboko_mms_catalog_product_index
    tree:
      application_menu:
        children:
          kiboko_pricing_tab:
            children:
              kiboko_pricing_history: ~

#  titles:
#    kiboko_price_list: Price List
